In [1]:
import pandas as pd 
import numpy as np 
import os, sys

In [2]:
data = pd.read_csv('parkinsons.data.txt')


In [4]:
predictors = data.drop(['name'], axis = 1)


In [6]:
predictors = predictors.drop(['status'], axis = 1).values

In [7]:
target = data['status']

In [8]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler((-1, 1))
X = scaler.fit_transform(predictors)
Y = target

In [9]:
import xgboost as xgb
from xgboost import XGBClassifier
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn import metrics
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = .25, random_state = 7)

In [10]:
model = XGBClassifier()
model.fit(X_train, Y_train)

XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, gamma=0,
              learning_rate=0.1, max_delta_step=0, max_depth=3,
              min_child_weight=1, missing=None, n_estimators=100, n_jobs=1,
              nthread=None, objective='binary:logistic', random_state=0,
              reg_alpha=0, reg_lambda=1, scale_pos_weight=1, seed=None,
              silent=None, subsample=1, verbosity=1)

In [11]:
y_pred = model.predict(X_test)
print("XGB boost:")
print(metrics.accuracy_score(Y_test, y_pred))
print(metrics.classification_report(Y_test, y_pred))
print(metrics.confusion_matrix(Y_test, y_pred))


XGB boost:
0.9591836734693877
              precision    recall  f1-score   support

           0       1.00      0.80      0.89        10
           1       0.95      1.00      0.97        39

    accuracy                           0.96        49
   macro avg       0.98      0.90      0.93        49
weighted avg       0.96      0.96      0.96        49

[[ 8  2]
 [ 0 39]]


Logistic Regression

In [12]:
from sklearn import datasets
from sklearn import metrics
from sklearn.linear_model import LogisticRegression

# fit a logistic regression model to the data

In [13]:
model = LogisticRegression()
model.fit(X_train, Y_train)
y_pred = model.predict(X_test)

# summarize the fit of the model

In [14]:
print("Logistic Regression: ")
print(metrics.accuracy_score(Y_test, y_pred))
print(metrics.classification_report(Y_test, y_pred))
print(metrics.confusion_matrix(Y_test, y_pred))

Logistic Regression: 
0.8775510204081632
              precision    recall  f1-score   support

           0       0.75      0.60      0.67        10
           1       0.90      0.95      0.92        39

    accuracy                           0.88        49
   macro avg       0.83      0.77      0.80        49
weighted avg       0.87      0.88      0.87        49

[[ 6  4]
 [ 2 37]]


Gaussian Naive Bayes

In [15]:
from sklearn import datasets
from sklearn import metrics
from sklearn.naive_bayes import GaussianNB
model = GaussianNB()
model.fit(X_train, Y_train)

GaussianNB(priors=None, var_smoothing=1e-09)

Make predictions

In [16]:
y_pred = model.predict(X_test)

summarize the fit of the model

In [17]:
print("Gaussian Naive Bayes:")
print(metrics.accuracy_score(Y_test, y_pred))
print(metrics.classification_report(Y_test, y_pred))
print(metrics.confusion_matrix(Y_test, y_pred))

Gaussian Naive Bayes:
0.6938775510204082
              precision    recall  f1-score   support

           0       0.38      0.80      0.52        10
           1       0.93      0.67      0.78        39

    accuracy                           0.69        49
   macro avg       0.65      0.73      0.65        49
weighted avg       0.82      0.69      0.72        49

[[ 8  2]
 [13 26]]


#K-Nearest Neighbor (BEST ONE 98%%)

In [18]:
from sklearn import datasets
from sklearn import metrics
from sklearn.neighbors import KNeighborsClassifier
model = KNeighborsClassifier()
model.fit(X_train, Y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

 Make predictions

In [19]:
y_pred = model.predict(X_test)

summarize the fit of the model

In [20]:
print("k-Nearest Neighbor: ")
print(metrics.accuracy_score(Y_test, y_pred))
print(metrics.classification_report(Y_test, y_pred))
print(metrics.confusion_matrix(Y_test, y_pred))


k-Nearest Neighbor: 
0.9795918367346939
              precision    recall  f1-score   support

           0       1.00      0.90      0.95        10
           1       0.97      1.00      0.99        39

    accuracy                           0.98        49
   macro avg       0.99      0.95      0.97        49
weighted avg       0.98      0.98      0.98        49

[[ 9  1]
 [ 0 39]]


# Support Vector Machine

In [24]:
from sklearn import datasets
from sklearn import metrics
from sklearn.svm import SVC
model = SVC()
model.fit(X_train, Y_train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

make predictions

In [25]:
y_pred = model.predict(X_test)

summarize the fit of the model

In [26]:
print("Support Vector Machine: ")
print(metrics.accuracy_score(Y_test, y_pred))
print(metrics.classification_report(Y_test, y_pred))
print(metrics.confusion_matrix(Y_test, y_pred))


Support Vector Machine: 
0.8979591836734694
              precision    recall  f1-score   support

           0       1.00      0.50      0.67        10
           1       0.89      1.00      0.94        39

    accuracy                           0.90        49
   macro avg       0.94      0.75      0.80        49
weighted avg       0.91      0.90      0.88        49

[[ 5  5]
 [ 0 39]]


Classification and Regression Trees

In [27]:
from sklearn import datasets
from sklearn import metrics
from sklearn.tree import DecisionTreeClassifier
model = DecisionTreeClassifier()
model.fit(X_train, Y_train)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=None, splitter='best')

 make predictions

In [28]:
y_pred = model.predict(X_test)

summarize the fit of the model

In [29]:
print("Classification and Regression Trees")
print(metrics.accuracy_score(Y_test, y_pred))
print(metrics.classification_report(Y_test, y_pred))
print(metrics.confusion_matrix(Y_test, y_pred))

Classification and Regression Trees
0.9591836734693877
              precision    recall  f1-score   support

           0       0.90      0.90      0.90        10
           1       0.97      0.97      0.97        39

    accuracy                           0.96        49
   macro avg       0.94      0.94      0.94        49
weighted avg       0.96      0.96      0.96        49

[[ 9  1]
 [ 1 38]]
